# Generated by Django 3.1.2 on 2020-12-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='items/default.png', upload_to='items/'),
        ),
    ]
