# Generated by Django 3.1.2 on 2020-12-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20201207_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_time_slot',
            field=models.CharField(blank=True, choices=[('m', 'Morning (9AM - 11AM'), ('n', 'Midday (12PM - 2PM)'), ('e', 'Evening (4PM - 6PM')], default='m', help_text='Choose a pick-up time slot for tomorrow.', max_length=1),
        ),
    ]
