# Generated by Django 3.1.2 on 2020-12-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20201209_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='fulfilled',
        ),
    ]
