# Generated by Django 3.1.2 on 2020-12-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20201209_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fulfilled',
            new_name='ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
    ]
